name: test CI

on:
  push:
    branches: 
    - master
  workflow_dispatch:
env:
  app: test
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: echo test
        run: echo "${{ github.ref_name }} and ${{ GITHUB_REF_NAME }} and $GITHUB_REF_NAME"
